# Generated by Django 3.0.5 on 2020-04-21 12:58

from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date of upload')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('ifile', models.ImageField(height_field='height', upload_to=image.models.get_upload_to, verbose_name='file', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, verbose_name='width')),
                ('height', models.PositiveIntegerField(editable=False, verbose_name='height')),
                ('size', models.PositiveIntegerField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Reform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('ifile', models.ImageField(height_field='height', upload_to=image.models.get_reform_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforms', to='image.Image')),
            ],
            options={
                'unique_together': {('image', 'filter_spec')},
            },
        ),
    ]
