# Generated by Django 3.1.1 on 2020-11-04 07:31

from django.db import migrations, models
import django.db.models.deletion
import image.model_fields
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of upload')),
                ('src', image.model_fields.ImageFileField(bytesize_field='bytesize', form_limit_filepath_length=True, height_field='height', max_length=55, max_size=2097152, unique=True, upload_to=image.models.get_image_upload_to, verbose_name='image_file', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, verbose_name='width')),
                ('height', models.PositiveIntegerField(editable=False, verbose_name='height')),
                ('bytesize', models.PositiveIntegerField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestReform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', image.model_fields.ReformFileField(max_length=55, unique=True, upload_to=image.models.get_reform_upload_to)),
                ('filter_id', models.CharField(db_index=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='test_image.testimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
